theme: jekyll-theme-minimal
title: Judith Neve <br>
description: <br> <b>Contact</b><br><a href="mailto:j.a.nevedemevergnies@uu.nl"> j.a.nevedemevergnies@uu.nl</a> | <a href="mailto:j.a.nevedemevergnies@umcutrecht.nl"> j.a.nevedemevergnies@umcutrecht.nl</a> | <a href="mailto:judith.nevedm@gmail.com"> judith.nevedm@gmail.com</a>.
logo: /img/me.png
auto_ids: true
