theme: jekyll-theme-minimal
title: Judith Neve <br>
description: <br> Soon-to-be graduate from Utrecht University with a Master's in Methodology and Statistics <br> Interested in communicating statistics and interdisciplinarity. <br><br> Contact:<a href="mailto:j.a.nevedemevergnies@uu.nl"> j.a.nevedemevergnies</a>.
logo: /img/me.png
auto_ids: true
