theme: jekyll-theme-minimal
title: Judith Neve <br>
description: <br><a href="https://judithneve.github.io/"> About me</a><br><a href="https://judithneve.github.io/projects.html"> Projects</a><br><a href="https://judithneve.github.io/CV.html"> CV</a><br><a href="https://judithneve.github.io/contact.html"> Contact</a>
logo: /img/me.png
auto_ids: true
